### ISSUE TITLE
startmoloch.sh fix

### ISSUE THREAD

**Issue by rskntroot** [mammo0/docker-moloch#1]
For those getting the output:

>Giving ES time to start...`
>
>ES started...
> Install Elasticsearch server locally for demo, must have at least 3G of memory, NOT recommended for production use (yes or no) [no] Moloch - Creating configuration files
> /data/moloch/bin/Configure: line 114: /data/moloch/etc/config.ini.sample: No such file or directory
> /data/moloch/bin/Configure: line 115: /data/moloch/etc/config.ini.sample: No such file or directory
> No startup scripts created for capture and viewer

Might want to add `echo $MOLOCH_LOCALELASTICSEARCH | ` at the beginning of line 18&30 in the scripts/startmoloch.sh

Also, thanks for sharing this, its been fun playing around with Moloch.

**Comment by mammo0** [comment]
Hello and thanks for this issue. Don't know why I didn't hit it myself...

The underlying problem however is the `Configure` script in Moloch, especially this line: https://github.com/arkime/arkime/blob/469df47c5bd8106a60cb0a355d1645df6604c767/release/Configure#L82
There the variable `MOLOCH_LOCALELASTICSEARCH` gets defined by the script. So it doesn't matter what is set by the environment.

I implemented your fix in the latest commit. If it still doesn't work, please reopen this issue.
